services:
  web:
    container_name: frontend_dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true

    #This is used to keep the container running and identify changes in the file system
    volumes:
      - ./:/app
      - /app/node_modules
    stdin_open: true

  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev

    environment:
      - CHOKIDAR_USEPOLLING=true

    volumes:
      - ./:/app
      - /app/node_modules

    stdin_open: true
    tty: true
    # Specify the command to run the tests
    command: ["npm", "run", "test", "--", "--watchAll"]
